# Numpy Arrays

Numpy Arrays are of two kinds. 1D Vectors and 2D Matrix.

In [1]:
# Importing Numpy

import numpy as np

In [3]:
# Creating a numpy array
mylist = [1,2,3,4]
mylist

[1, 2, 3, 4]

In [4]:
numpy_array = np.array(mylist)
numpy_array

array([1, 2, 3, 4])

In [5]:
# This is a numpy array 1D

In [6]:
# Creating a 2D Array

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
numpy_2Darray = np.array(my_mat)
numpy_2Darray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# This is a 2D array. It can also be seen from how it is displayed.
# This array contains 3 rows and 3 columns.

## Numpy objects to create arrays quickly

#### 1. np.arange()

In [8]:
# SImilar to range function

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2) # Upto 10 and step size of 2

array([ 0,  2,  4,  6,  8, 10])

#### 2. np.zeros()

In [10]:
# Creating an array with all zero elements

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((5,4))

# The parameter should be passed as a tuple
#The first digit represent the number of rows and the second digit represents the number of columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 3. np.ones()

In [14]:
# Creating an array with all elements as one

np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,4))

# Similar to zeros

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 4. np.linspace()

In [20]:
# This is similar to arange but the parameters have different meanings
np.linspace(0,2,10)

# The onening range and closing range both are included
# The third argument is the number of total points required - should always be int

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

#### 5. np.eye()

In [21]:
# Creating an Identity Matrix

np.eye(5)

# This gives an outpur as a 5X5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(2,3)

# This however cannot be called as an identity matrix. Though still useful

array([[1., 0., 0.],
       [0., 1., 0.]])

#### 6.np.random.rand()

In [28]:
# Helps create a matrix of given size with values populated from a uniform distribution

# uniform distribution is the key here

np.random.rand(5)

array([0.22613822, 0.9610844 , 0.04074985, 0.99038245, 0.76281707])

In [29]:
np.random.rand(5,4)

array([[0.78918596, 0.40266395, 0.2942064 , 0.87852921],
       [0.09555404, 0.65443712, 0.80128745, 0.89651624],
       [0.81215593, 0.1620837 , 0.77424383, 0.88975082],
       [0.64065074, 0.06810083, 0.01641535, 0.06638994],
       [0.37755532, 0.60206857, 0.63428651, 0.56113075]])

#### 7.np.random.randn()

In [30]:
# Helps create a matrix of given size with values populated from a normal or gaussian distribution

# normal distribution is the key here

np.random.randn(5)

array([0.32261432, 2.05539246, 0.7350285 , 1.2749207 , 0.19829429])

In [31]:
np.random.randn(5,4)

array([[ 0.17977429, -0.07794975,  1.27864751,  1.26619252],
       [-0.04036055, -1.78413292, -1.91343821,  1.22987921],
       [ 0.65598996, -3.08633025, -1.15538578,  0.0984787 ],
       [-1.17356131,  0.0353197 , -0.45521469, -1.16470294],
       [-0.03827763, -1.4913082 ,  0.89923394, -1.96525346]])

#### 8.np.random.randint()

In [35]:
# Helps creating an array of random integers in a given range

np.random.randint(0,100,10)

# Lower bound is inclusive and the higher bound is exclusive

# Third argument specifies the number of elements required

array([28, 20, 98, 72, 30, 54,  5, 44, 92, 12])

In [38]:
# If we dont include the third argument it just returns one number

np.random.randint(0,100)

5

## Some useful attributes and methods of an array

In [39]:
# let's difine two arrays to show these functions

arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
randarr = np.random.randint(0,100,10)
randarr

array([99, 28, 27, 59, 17,  1, 53, 57, 13, 38])

#### 1. Reshape mehod

In [42]:
arr.reshape(5,5)

# make sure that the number of elements in the previous array and the number of elements required in the new one
# must be equal

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 2. Max and Min method

In [45]:
randarr.max()

# Returns the maximum value in an array

99

In [46]:
randarr.min()

# Returns the minimum value in an array

1

#### agrmin and argmax methods

In [47]:
randarr.argmax()

# Returns the index location of the maximum value

0

In [48]:
randarr.argmin()

# Returns the index location of the minimum value

5

#### shape attribute

In [50]:
arr.shape

# This is an attribute therefore, paranthesis is not to be used

(25,)

In [51]:
# A single value denotes 1D array

reshaped_arr = arr.reshape(5,5)
reshaped_arr.shape

(5, 5)

#### dtype attribute

In [53]:
arr.dtype

dtype('int32')

In [ ]:
# This shows the datatype of the elements of the array

# NumPy - Indexing, Selection and Operations

In [1]:
import numpy as np

In [2]:
# Creating an example numpy array

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Indexing and Selection

In [3]:
# Selecting the element at a specified position

arr[8] # Same as lists

8

In [4]:
# Selecting a sub-array using slicing 

arr[1:5]

array([1, 2, 3, 4])

In [5]:
# Similar to lists
# outter bound is not included

In [6]:
arr[4:]

# Upto the end. Can also be used for the first position

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
# Slicing can also be used for assignment

arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# Slicing is a refrencing method. See the Example below
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_array = arr[:4]
slice_of_array

array([0, 1, 2, 3])

In [15]:
slice_of_array[:] = 20
slice_of_array

array([20, 20, 20, 20])

In [16]:
# Calling the original array
arr

array([20, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# THe values have been changed here as well.

# To specifically create a copy use the copy method

arr_copy = arr.copy()
arr_copy

array([20, 20, 20, 20,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# Any changes to arr_copy now wont affect the original arr

## Indexing a 2D Array

In [20]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]]) # Can be initiated by a list of lists
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
# Selecting a single element
arr_2d[0][0]

5

In [22]:
# the above can also be done by a single brakect notation rather than double bracket notation

In [23]:
arr_2d[0,0]

5

In [27]:
# We can use colon to select a particular sub-array

arr_2d[0:2,1:3]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [29]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# using a comparison operator on an aray yeilds another array of same dimensions with the results of individual caomparisons

# dtype of the new array is boolean

arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [31]:
# if we pass the boolean array into the old array then it gives a new array with values where the conditions 
# were true

bool_array = arr>5

arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [32]:
# The dimensions are different from the original array

In [33]:
# Executing this in a single step

arr[arr<3]

array([0, 1, 2])

In [35]:
# Implementing conditional selection on 2d arrays

arr_2d[arr_2d>25]

array([30, 35, 40, 45])

# Numpy Operators

In [36]:
# There can be three kinds of operations when arrays are concerned
# 1. Arrays with Arrays
# 2. Arrays with Scalars
# 3. Functions implemented on arrays

# let's see our example arrays

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# Adding two arrays

arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [40]:
arr / arr

C:\Users\sahar\AppData\Local\Temp/ipykernel_13972/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
0/0

ZeroDivisionError: division by zero

In [42]:
# In numpy division by zero leads to a warning where as without numpy it is an error

In [43]:
# Dealing with scalars and an array

arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [44]:
# What numpy does is it broadcasts the scalar to every element in the array
# Works with all the four mathematical operators

In [45]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [46]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [47]:
arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [50]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [48]:
# this can be executed like an equation. The order between just a single operator doesn't matter

1 + arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
1 / arr

C:\Users\sahar\AppData\Local\Temp/ipykernel_13972/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

## numpy functions on arrays

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
# sqrt function - squareroot of every element

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [53]:
# exp function - exp of every funcrion (power of e)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [55]:
# max value among all the elements in the array

np.max(arr)

10

In [56]:
# min value among all the elements in the array

np.min(arr)

0

In [58]:
# for min and max we can call the method directly off the array

arr.max()

10

In [59]:
# Trignometric function

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [60]:
# Log function

np.log(arr)

C:\Users\sahar\AppData\Local\Temp/ipykernel_13972/113375872.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [61]:
# numpy has most of the basic mathematical functions and some complex ones too
# visit the documentation page to check

In [62]:
# There also are functions that dont only work on individual values but give out the aggregate of all the values

np.sum(arr)

55

In [63]:
np.average(arr)

5.0

In [64]:
# Standatd Deviation of all the values

np.std(arr)

3.1622776601683795

In [67]:
# for doing the operation row wise or column wise we can specify the axis

np.sum(arr_2d,axis=0)

array([60, 75, 90])

In [68]:
np.std(arr_2d,axis=1)

array([4.0824829, 4.0824829, 4.0824829])